# Generated by Django 5.0.14 on 2026-05-20 06:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Configuration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nvidia_api_key', models.CharField(blank=True, help_text='Your Nvidia API Key from build.nvidia.com', max_length=255)),
                ('model_name', models.CharField(default='meta/llama-3.3-70b-instruct', help_text='The Nvidia NIM model to use', max_length=100)),
                ('workspace_path', models.CharField(blank=True, help_text='Path to the workspace where agent edits files', max_length=500)),
            ],
            options={
                'verbose_name': 'Configuration',
                'verbose_name_plural': 'Configurations',
            },
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('skill_name', models.CharField(help_text='The name of the skill applied to this session', max_length=100)),
                ('status', models.CharField(choices=[('idle', 'Idle'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='idle', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('system_prompt', models.TextField(blank=True, help_text='System prompt sent to the LLM')),
                ('workspace_dir', models.CharField(blank=True, help_text='Session-specific workspace subfolder', max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=20)),
                ('content', models.TextField(blank=True, default='')),
                ('tool_calls', models.JSONField(blank=True, help_text='List of tool calls made by the assistant', null=True)),
                ('tool_call_id', models.CharField(blank=True, help_text='ID of the tool call this message answers', max_length=100, null=True)),
                ('name', models.CharField(blank=True, help_text='The name of the tool called', max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='core.session')),
            ],
            options={
                'ordering': ['created_at', 'id'],
            },
        ),
    ]
